services:
  localstack:
    image: localstack/localstack:4.9.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=0
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"

  tempo:
    image: grafana/tempo:2.9.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "4318:4318" # OTLP HTTP
      - "4317:4317" # OTLP gRPC
      - "3200:3200" # Tempo UI

  grafana:
    image: grafana/grafana:12.2.0
    volumes:
      - ${PWD}/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000" # Grafana UI
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true